// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  three_dee_hero: dynamic(() => import("./ThreeDeeHero")),
};
