// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  three_dee_hero: dynamic(() => import("./ThreeDeeHero")),
};
